<div align="left" style="background-color: #008080; padding: 20px 10px;">
<h3><b>IDEAS - Institute of Data Engineering, Analytics and Science Foundation</b></h3>
<p>Summer Internship Program 2026</p>
<hr style="width:100%;">
<h3><b>Project Title:</b> Fake News Detection and Evaluation with Confusion Matrix</h3>
<h4>Project Notebook</h4>

<blockquote style="border-left: 4px solid #4285F4; padding-left: 15px;">
  <strong>Created by:</strong> Suprava Das<br>
  <strong>Designation:</strong> Associate Software Developer
</blockquote>
<hr style="width:100%;">
</div>

## Project Goal: Automated Fake News Classification

The core task of this project is to develop and evaluate a machine learning system for identifying fake news.

**Objectives:**
*   Train a classification model on a labeled dataset of news articles.
*   Use textual data (title and content) as the primary features.
*   Evaluate the model's effectiveness using standard metrics, including a confusion matrix to analyze true vs. false positives and negatives.

---

## Dataset Overview

The project utilizes a publicly available dataset composed of two distinct classes of news content.

*   **Source of True Articles:**
    *   **Website:** `Reuters.com`
    *   **Description:** A reputable, mainstream news provider.

*   **Source of Fake Articles:**
    *   **Websites:** Various platforms identified by Politifact and Wikipedia.
    *   **Description:** Sources known for producing unreliable or intentionally false information.

*   **Content Focus:** The articles primarily cover topics related to politics and world news.

*   **Download Link:** The dataset is available on Kaggle at [www.kaggle.com/datasets/emineyetm/fake-news-detection-datasets](https://www.kaggle.com/datasets/emineyetm/fake-news-detection-datasets).

### Question 1: Import Libraries and Load Data (2 Marks)

Import `pandas` as `pd`. Load the `Fake.csv` and `True.csv` datasets into two separate DataFrames named `fake_df` and `true_df` respectively. Display the first 3 rows of `fake_df`.

**Expected Output:** A table showing the first 3 rows of the fake news dataset.

In [4]:
import pandas as pd
fake_df=pd.read_csv("/content/fake.csv")
true_df=pd.read_csv("/content/true.csv")
fake_df.head(3)

,Who Disrespects Our Flag or Law Enforcement On Notice…YOU’LL BE FIRED!,"Several team owners said they would come down hard on any drivers who did not stand during the national anthem. That included NASCAR legend Richard Petty, owner of Richard Petty Motorsports. Anybody that don t stand up for the anthem oughta be out of the country, period, Petty said (via the Associated Press). What got em where they re at? The United States. When Petty was asked if his drivers would be fired if they protest during the anthem as Trump called for, Petty emphatically said, You re right. Richard Petty Motorsports currently employs Bubba Wallace, who recently became the first black driver in a NASCAR race in over a decade.Richard Childress, owner of Richard Childress Racing, also said he would not tolerate any drivers who do not stand during the anthem. It ll get you a ride on a Greyhound bus, Childress said. Anybody that works for me should respect the country we live in. So many people gave their lives for it. This is America. All drivers reportedly stood during the anthem prior to Sunday s race in New Hampshire.For entire story: Business Insider",politics,"Sep 25, 2017"
0,WILL AND GRACE Writers Explain How Their HATE ...,When Will & Grace creators David Kohan and Max...,politics,"Sep 25, 2017"
1,NY Giants Player Pretends to ‘Pee Like a Dog’ ...,New York Giants player Odell Beckham Jr. score...,politics,"Sep 25, 2017"
2,Redskins Player Has Tantrum: ‘We’re being tear...,"I respect the office, I respect the troops of...",politics,"Sep 25, 2017"

### Question 2: Create a 'class' Column (1 Mark)

To prepare for merging, add a new column named `class` to each DataFrame. Assign the integer `1` to this column for `fake_df` and `0` for `true_df`. Display the last 3 rows of `true_df` to verify.

**Expected Output:** A table showing the last 3 rows of the true news dataset with the new 'class' column containing zeros.

In [5]:
fake_df['class']=1
true_df['class']=0
true_df.tail(3)

,title,text,subject,date,class
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

### Question 3: Merge and Shuffle DataFrames (2 Marks)

Merge `fake_df` and `true_df` into a single DataFrame called `df`. Then, shuffle the rows of this new DataFrame to randomize the order of true and fake news articles. Display the first 10 rows of the shuffled DataFrame.

**Expected Output:** A table showing 10 random rows from the combined dataset.

In [6]:
df=pd.concat([fake_df,true_df],ignore_index=True)
df=df.sample(frac=1).reset_index(drop=True)
df.head(10)

,Who Disrespects Our Flag or Law Enforcement On Notice…YOU’LL BE FIRED!,"Several team owners said they would come down hard on any drivers who did not stand during the national anthem. That included NASCAR legend Richard Petty, owner of Richard Petty Motorsports. Anybody that don t stand up for the anthem oughta be out of the country, period, Petty said (via the Associated Press). What got em where they re at? The United States. When Petty was asked if his drivers would be fired if they protest during the anthem as Trump called for, Petty emphatically said, You re right. Richard Petty Motorsports currently employs Bubba Wallace, who recently became the first black driver in a NASCAR race in over a decade.Richard Childress, owner of Richard Childress Racing, also said he would not tolerate any drivers who do not stand during the anthem. It ll get you a ride on a Greyhound bus, Childress said. Anybody that works for me should respect the country we live in. So many people gave their lives for it. This is America. All drivers reportedly stood during the anthem prior to Sunday s race in New Hampshire.For entire story: Business Insider",politics,"Sep 25, 2017",class,title,text,subject,date
0,NaN,NaN,NaN,NaN,0,Brazil Senate to vote on fiscal package on Tue...,BRASILIA (Reuters) - The Brazilian Congress is...,worldnews,"September 5, 2017"
1,NaN,NaN,NaN,NaN,0,Senator Rubio: Hackers targeted former preside...,WASHINGTON (Reuters) - U.S. Senator Marco Rubi...,politicsNews,"March 30, 2017"
2,OBAMA HOSTS FUNDRAISER: Praises Clinton For Gr...,Obama hosted a fundraiser for a bunch of wealt...,politics,"Aug 16, 2016",1,NaN,NaN,NaN,NaN
3,“Unvetted” Illegals Turn Germany Into A Third-...,Take Notes America! Germany s Angela Merkel ha...,Government News,"Dec 16, 2015",1,NaN,NaN,NaN,NaN
4,"In 2017, America’s liberal abortion agenda loo...","21st Century Wire says Here s an unusual, but ...",US_News,"August 17, 2017",1,NaN,NaN,NaN,NaN
5,REMEMBER WHEN Democrat Operatives Were Caught ...,Watch:. @Jordanfabian If there is no #VoterFra...,left-news,"Nov 28, 2016",1,NaN,NaN,NaN,NaN
6,"Katy Perry, Christina Aguilera, Kim and Kanye,...",There s so much diversity in the Democrat pres...,left-news,"Oct 13, 2015",1,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,0,"Illinois House passes $5 billion tax package, ...",CHICAGO (Reuters) - Illinois’ Democratic-contr...,politicsNews,"July 3, 2017"
8,NaN,NaN,NaN,NaN,0,Trump backers' disparate hopes coalesce around...,WASHINGTON (Reuters) - The pomp and circumstan...,politicsNews,"January 20, 2017"
9,NaN,NaN,NaN,NaN,0,Dangerous hurricane Irma moving towards Caribb...,"(Reuters) - Irma, now a category 4 , is headin...",worldnews,"September 5, 2017"

### Question 4: Data Cleaning (2 Marks)

Create a new DataFrame `df_clean` by dropping the `title`, `subject`, and `date` columns from `df`. Then, reset the index of `df_clean`. Print the first 5 rows of `df_clean`.

**Expected Output:** A table with 5 rows and 2 columns ('text' and 'class').

In [7]:
df_clean=df.drop(columns=['title','subject','date'])
df_clean=df_clean.reset_index(drop=True)
df_clean.head(5)

,Who Disrespects Our Flag or Law Enforcement On Notice…YOU’LL BE FIRED!,"Several team owners said they would come down hard on any drivers who did not stand during the national anthem. That included NASCAR legend Richard Petty, owner of Richard Petty Motorsports. Anybody that don t stand up for the anthem oughta be out of the country, period, Petty said (via the Associated Press). What got em where they re at? The United States. When Petty was asked if his drivers would be fired if they protest during the anthem as Trump called for, Petty emphatically said, You re right. Richard Petty Motorsports currently employs Bubba Wallace, who recently became the first black driver in a NASCAR race in over a decade.Richard Childress, owner of Richard Childress Racing, also said he would not tolerate any drivers who do not stand during the anthem. It ll get you a ride on a Greyhound bus, Childress said. Anybody that works for me should respect the country we live in. So many people gave their lives for it. This is America. All drivers reportedly stood during the anthem prior to Sunday s race in New Hampshire.For entire story: Business Insider",politics,"Sep 25, 2017",class,text
0,NaN,NaN,NaN,NaN,0,BRASILIA (Reuters) - The Brazilian Congress is...
1,NaN,NaN,NaN,NaN,0,WASHINGTON (Reuters) - U.S. Senator Marco Rubi...
2,OBAMA HOSTS FUNDRAISER: Praises Clinton For Gr...,Obama hosted a fundraiser for a bunch of wealt...,politics,"Aug 16, 2016",1,NaN
3,“Unvetted” Illegals Turn Germany Into A Third-...,Take Notes America! Germany s Angela Merkel ha...,Government News,"Dec 16, 2015",1,NaN
4,"In 2017, America’s liberal abortion agenda loo...","21st Century Wire says Here s an unusual, but ...",US_News,"August 17, 2017",1,NaN

### Question 5: Define a Text Preprocessing Function (5 Marks)

Define a Python function named `wordopt(text)` that takes a string, converts it to lowercase, removes URLs, removes all non-alphanumeric characters (replacing them with spaces), and replaces multiple spaces with a single space. Apply this function to the 'text' column of `df_clean`.

**Expected Output:** No direct output. The 'text' column in `df_clean` will be processed.

In [16]:
import re
import pandas as pd

def wordopt(text):

  if pd.isna(text):
    return ""
  text=text.lower()
  text=re.sub(r'http\S+|www\S+','',text)
  text=re.sub(r'[^a-z0-9\s]',' ',text)
  text=re.sub(r'\s+',' ',text).strip()
  return text

df_clean['text']=df_clean['text'].apply(wordopt)

### Question 6: Feature and Target Split (2 Marks)

Define your feature `x` as the 'text' column from `df_clean` and your target `y` as the 'class' column. Then, use `train_test_split` to create `x_train`, `x_test`, `y_train`, and `y_test`. Use a `test_size` of 0.25.

**Expected Output:** No direct output. The data split variables will be created.

In [18]:
from sklearn.model_selection import train_test_split
x=df_clean['text'].fillna('') # Explicitly fill NaN values with empty strings
y=df_clean['class']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

### Question 7: Text to Vectors using TF-IDF (5 Marks)

Import `TfidfVectorizer` from `sklearn.feature_extraction.text`. Create an instance, fit it on `x_train`, and then transform both `x_train` and `x_test` into numerical vectors named `xv_train` and `xv_test`.

**Expected Output:** No direct output. The vectorized training and testing data will be ready.

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
xv_train=vectorizer.fit_transform(x_train.astype(str))
xv_test=vectorizer.transform(x_test.astype(str))

### Question 8: Train and Evaluate a Logistic Regression Model (3 Marks)

Import `LogisticRegression`. Create an instance, train it on the vectorized training data (`xv_train`, `y_train`), and make predictions on `xv_test`. Finally, print the `classification_report` for the model's performance.

**Expected Output:** A text-based classification report for the Logistic Regression model.

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
lr_model=LogisticRegression()
lr_model.fit(xv_train,y_train)
lr_pred=lr_model.predict(xv_test)
print(classification_report(y_test,lr_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5313
           1       1.00      1.00      1.00      3455

    accuracy                           1.00      8768
   macro avg       1.00      1.00      1.00      8768
weighted avg       1.00      1.00      1.00      8768

### Question 9: Train and Evaluate a Decision Tree Model (3 Marks)

Import `DecisionTreeClassifier` from `sklearn.tree`. Create an instance, train it on `xv_train` and `y_train`, predict on `xv_test`, and print the `accuracy_score`.

**Expected Output:** A single decimal number representing the accuracy of the Decision Tree model.

In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
dt_model=DecisionTreeClassifier()
dt_model.fit(xv_train,y_train)
dt_pred=dt_model.predict(xv_test)
print(accuracy_score(y_test,dt_pred))

0.9998859489051095

### Question 10: Hyperparameter Tuning with GridSearchCV (5 Marks)

Your `LogisticRegression` model used default parameters. Let's find better ones using `GridSearchCV`. Import it from `sklearn.model_selection`. Perform a grid search on a `LogisticRegression` model using the `xv_train` and `y_train` data.

Use the following parameter grid:
```python
param_grid = {'C': [0.1, 1, 10], 'solver': ['liblinear', 'lbfgs']}
```
After fitting, print the `best_params_` found by the grid search.

**Expected Output:** A dictionary showing the best 'C' and 'solver' values found.

In [23]:
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1, 1, 10],'solver':['liblinear','lbfgs']}
grid_search=GridSearchCV(LogisticRegression(),param_grid,cv=5)
grid_search.fit(xv_train,y_train)
print(grid_search.best_params_)

{'C': 10, 'solver': 'liblinear'}